### PR TITLE
adds small suggestions

### PR DESCRIPTION
**Pull request by Nowosad**
Hi @loreabad6 -- I added some suggestions in this PR. In general, I think that the code examples are good and they are enough for one hour. I would suggest adding some text, links, comments, etc. that people could read after the course. 

I also have a few other questions/comments:

1. I was unable to render the book with the `references.bib` (- "https://api.citedrive.com/bib/f67c224b-6fcd-4870-87fc-67374abf013e/references.bib?x=eyJpZCI6ICJmNjdjMjI0Yi02ZmNkLTQ4NzAtODdmYy02NzM3NGFiZjAxM2UiLCAidXNlciI6ICIyNTY4IiwgInNpZ25hdHVyZSI6ICJiZmJhYzUyOThkY2E0ZWI4MjZjNjVkMDQ5MDc2N2I0OGVmMjQ1ZmI4ODMwYmVhYjllYmIwNmJiMTY0MWVlYThmIn0=/bibliography.bib")
2. Intro to R-spatial: you can also add another image from https://bakaniko.github.io/foss4g2022-getting-started-rspatial/rspatial.html#raster-data about terra. Maybe it is also worth to mention the difference between R-spatial and Rspatial (or just mention Spatial CRAN Task View; or mention that there are many R spatial packages; or list a few unique ones)
3. How can the people at the course get the river data?
4. I think it would be good to add a few callout blocks (https://quarto.org/docs/authoring/callouts.html), e.g., mentioning other possible spatial operations, applications, additional packages (e.g., tinyterra and ggspatial after introducing ggplot2), etc.

### CODE REVIEW

**Comment by edzer** [comment]
@Nowosad out of interest: is that terra Python module actually existing?

**Comment by Nowosad** [comment]
@edzer Good question. I've never seen it. Also -- I've never seen terra C++ used directly from a command line either. I do not think it exist (at least in the open).

**Comment by edzer** [comment]
In that case the figure is somewhat misleading.

**Comment by Nowosad** [comment]
Yep, you are right. It is from one of the @rhijmans talks, but it should be edited before adding to the course materials.

**Comment by loreabad6** [comment]
Hi @Nowosad, 
Thanks for the changes and suggestions. I will definitely add text and links, hopefully manage between the weekend and coming week. 

> 1. I was unable to render the book with the references.bib

There was a [bug in Quarto](https://github.com/quarto-dev/quarto-cli/issues/8814), it is fixed at the devel version. I expect Quarto 1.5 to be out there soon. 

> 2. Intro to R-spatial: ...

I will definitely add the task view and give a further look at the terra image, given the exchange above with @edzer 

> 3. How can the people at the course get the river data?

The data is on the repo. I will add options to read from a raw file on GitHub or to download the data locally. I'll of course add links to the original data source. 

> 4. I think it would be good to add a few callout blocks

Yes thank you! I am a big fan of callout blocks so I'll definitely add them here and there.

Thank you again!

**Comment by loreabad6** [comment]
@Nowosad and @edzer I found this video from the presentation with the terra figure explained: https://youtu.be/5b2xhqlH49I?t=690. Having that clarified, I will include the figure and explain it accordingly. In essence, the Python module could be implemented but is not there yet, and the Rcpp part is just explaining how terra works (written in C++ and translated into R with Rcpp)

**Comment by edzer** [comment]
> but is not there yet

Yes, and we don't have an E.T.A. You could also say that being written in C++ means in many cases faster, but also harder to understand, debug or modify.

**Pull request merged**
